# Generated by Django 3.0.8 on 2020-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_worker_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_reg',
            name='ward',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
