# Generated by Django 3.0.8 on 2020-11-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_worker_reg_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=100)),
                ('c_contact', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.User_reg')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.Worker_reg')),
            ],
        ),
    ]
