# Generated by Django 3.0.8 on 2020-11-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
