# Generated by Django 3.0.8 on 2020-11-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_children_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
