# Generated by Django 3.0.8 on 2020-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0008_children_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('descri', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=100)),
                ('eventtime', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
