# Generated by Django 3.0.8 on 2020-11-22 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccination', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='decease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
