# Generated by Django 3.0.8 on 2020-11-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0010_auto_20201122_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='decease',
            new_name='disease',
        ),
    ]
