# Generated by Django 3.0.8 on 2020-11-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0012_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqty', models.CharField(max_length=100)),
                ('rdate', models.CharField(max_length=100)),
                ('rstatus', models.CharField(max_length=100)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.User_reg')),
                ('vacci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.Worker_reg')),
            ],
        ),
    ]
