# Generated by Django 3.0.8 on 2020-11-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0014_auto_20201123_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='message',
        ),
        migrations.AddField(
            model_name='allocate',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.Children'),
        ),
    ]
