# Generated by Django 3.0.8 on 2020-12-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0015_auto_20201123_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate',
            name='tstatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
