# Generated by Django 3.0.8 on 2020-12-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0016_allocate_tstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='vdate',
        ),
    ]
