# Generated by Django 3.0.8 on 2021-01-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0018_vaccine_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='period',
        ),
    ]
